---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: spring-music

outputs:
- name: current-app-info

run:
  path: spring-music/ci/tasks/current-app-get-info
