---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: "latest"

inputs:
- name: spring-music
#
#outputs:
#- name: app-artifact-output

run:
  path: spring-music/ci/tasks/run-unit-tests
