---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: spring-music

run:
  path: spring-music/ci/tasks/run-unit-tests
